Accessibility_Test:
  image:
    name: 'maven:3.6-jdk-11'
  before_script:
    - apt-get update
    - apt-get install -y xvfb
    - apt-get install -y zip
    - apt-get install -y wget
    - apt-get install -y ca-certificates
    - >-
      apt-get install -y libnss3-dev libasound2 libxss1 libappindicator3-1
      libindicator7 gconf-service libgconf-2-4 libpango1.0-0 xdg-utils
      fonts-liberation libgbm1
    - >-
      wget
      http://archive.ubuntu.com/ubuntu/pool/main/libu/libu2f-host/libu2f-udev_1.1.4-1_all.deb
    - dpkg -i libu2f-udev_1.1.4-1_all.deb
    - apt-get -y install libvulkan1
    - >-
      wget
      https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome*.deb
    - rm google-chrome*.deb
    - >-
      wget -N
      http://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - chmod +x chromedriver
  script:
    - mvn clean test
  allow_failure: true
